modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "MIT" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "dawnoftimebuilder" #mandatory
version = "1.5.53" #mandatory
displayName = "Dawn Of Time" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
authors = "Poulpinou & TheGoldenWorld" #optional
description = '''This mod adds many blocks and items from different cultures.''' #mandatory (Supports multiline text)

[[dependencies.dawnoftimebuilder]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47.2.20,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.dawnoftimebuilder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1, 1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dawnoftimebuilder]]
modId = "fusion"
mandatory = false
versionRange = "[1.0.0,2.0.0)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "dawnoftimebuilder.mixins.json"