modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="zrikons_furniture_medieval"
version="1.0.2"
displayName="Zrikon's Furniture : Medieval"
displayURL="https://discord.gg/tJ4UWF7sc6"
credits="https://discord.gg/tJ4UWF7sc6"
authors="zrikon"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.zrikons_furniture_medieval]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration