modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="dragnloextras"
version="1.1"
displayName="DragN's Livestock Overhaul: Scraps & Extras Addon!"
logoFile="scraps_logo.png"
authors="DragN0007"
description='''
An addon to Livestock Overhaul that adds hygiene, welfare, diseases and ailments, genetic traits, and other extra items/ features.
'''
[[dependencies.dragnloextras]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.dragnloextras]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.dragnloextras]]
modId="geckolib"
mandatory=true
versionRange = "[4.4.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.dragnloextras]]
modId="dragnlivestock"
mandatory=true
versionRange = "[3.8,)"
ordering="NONE"
side="BOTH"
[[dependencies.dragnloextras]]
modId="dragnpets"
mandatory=true
versionRange = "[2.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.dragnloextras]]
modId="jade"
mandatory=false
versionRange = "[11.11.1,)"
ordering="NONE"
side="BOTH"
mixinConfigs = [
    "mixins.dragnloextras.json",
    "mixins.dragnloextras.wildhorse.json"
]