modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="seedbags"
version="1.0.1"
displayName="Medieval Seedbags"
displayURL="https://curseforge.com/minecraft/mc-mods/medieval-seedbags"
credits="https://www.youtube.com/@nocubemc"
authors="NoCube"
description="Compact storage of seeds. Also good for decoration."

[[dependencies.seedbags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




