modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
logoFile="assets/saintsdragons/saintsdragons.png"

[[mods]]
modId="saintsdragons"
version="0.9.76"
displayName="Saint's Dragons"
displayURL="https://raevyx.miraheze.org/wiki/Main_Page"
description='''
i can write whatever i want. what are you gonna do? throw shoes at me?
'''
authors="Leon Saint"

[[dependencies.saintsdragons]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.saintsdragons]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.saintsdragons]]
modId="geckolib"
mandatory=true
versionRange="[4.8.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.saintsdragons]]
modId="emi"
mandatory=false
versionRange="[1.1.22,)"
ordering="AFTER"
side="CLIENT"
