license = "AllRightsReserved"
issueTrackerURL = "https://github.com/ApexStudios-Dev/FantasyFurniture/issues"

[[mods]]
modId = "fantasyfurniture_nordic"
version = "${file.jarVersion}"
displayName = "Fantasy's Furniture - Nordic"
credits = "Apex - Programming"
authors = "ApexStudios"
description = "Nordic Furniture set for Fantasy's Furniture"
bannerFile = "banner.png"
iconFile = "icon.png"
displayURL = "https://modrinth.com/project/fantasys-furniture-nordic"

[[dependencies.fantasyfurniture_nordic]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,26.4)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fantasyfurniture_nordic]]
modId = "neoforge"
type = "required"
versionRange = "[26.3-alpha,26.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fantasyfurniture_nordic]]
modId = "apexcore"
type = "required"
versionRange = "[26.3,26.4)"
[dependencies.fantasyfurniture_nordic.mc-publish]
modrinth = "xl3myxch"
curseforge = "550778"
[[dependencies.fantasyfurniture_nordic]]
modId = "fantasyfurniture"
type = "required"
versionRange = "[26.3-alpha,26.4)"
[dependencies.fantasyfurniture_nordic.mc-publish]
modrinth = "A0nfCqYw"
curseforge = "579564"