# This is the config dependency file for Lithium.
# This file should not be modified!
#
mixin.ai.nearby_entity_tracking=mixin.util.entity_section_position:true
mixin.ai.pathing=mixin.util.chunk_access:true
mixin.block.hopper=mixin.util.entity_movement_tracking:true,mixin.util.block_entity_retrieval:true,mixin.util.inventory_change_listening:true
mixin.block.hopper.worldedit_compat=mixin.util.block_entity_retrieval:true
mixin.entity.collisions.fluid=mixin.util.block_tracking:true,mixin.experimental.entity.block_caching.fluid_pushing:false
mixin.entity.collisions.intersection=mixin.util.block_tracking:true,mixin.util.chunk_access:true
mixin.entity.collisions.movement=mixin.util.chunk_access:true
mixin.entity.collisions.unpushable_cramming=mixin.chunk.entity_class_groups:true
mixin.experimental.entity.block_caching=mixin.util.block_tracking.block_listening:true
mixin.experimental.entity.block_caching.block_support=mixin.util.block_tracking.block_listening:true
mixin.experimental.entity.block_caching.block_touching=mixin.util.block_tracking.block_listening:true
mixin.experimental.entity.block_caching.fluid_pushing=mixin.util.block_tracking.block_listening:true
mixin.experimental.entity.block_caching.suffocation=mixin.util.block_tracking.block_listening:true
mixin.util.entity_movement_tracking=mixin.util.entity_section_position:true
mixin.util.inventory_comparator_tracking=mixin.util.block_entity_retrieval:true
mixin.world.block_entity_ticking.world_border=mixin.util.world_border_listener:true
