modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="entity_player_compat"
version="2.2.1"
displayName="Entity Player Compat"
authors="Exers"
description="Compatibility bridge between Entity Model Features and PlayerAnimator."

[[dependencies.entity_player_compat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.entity_player_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"

[[dependencies.entity_player_compat]]
modId="playeranimator"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.entity_player_compat]]
modId="entity_model_features"
mandatory=true
versionRange="[3.2,)"
ordering="NONE"
side="CLIENT"
