modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/Luke100000/ImmersiveFurniture/issues"

[[mods]]
modId = "immersive_furniture"
version = "0.3.3+1.20.1"
displayName = "Immersive Furniture"
displayURL = "https://conczin.net/"
logoFile = "icon.png"
credits = ""
authors = "Luke100000"
description = '''Create custom and fancy furniture, deco, and objects in-game or choose from a vast online library.'''
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.immersive_furniture]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_furniture]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1, 1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_furniture]]
modId = "ferritecore"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_furniture]]
modId = "packetfixer"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
