modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mods]]
modId="icys_better_horses"
version="2.0.1"
displayName="Icy's Better Horses"
logoFile="assets/icys-better-horses/icon.png"
authors="Icy"
credits=""
description='''Better Horses turns horses into long-term companions with bonding, commands, utility gear, and travel-focused upgrades.'''

[[mixins]]
config="icys_better_horses.mixins.json"

[[dependencies.icys_better_horses]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.icys_better_horses]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.icys_better_horses]]
modId="geckolib"
mandatory=true
versionRange="[4.7.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.icys_better_horses]]
modId="patchouli"
mandatory=false
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
