modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="butchery"
version="5.2"
displayName="Butchery"
displayURL="https://discord.gg/4jyFpT8jEk"
credits="Made with Mcreator"
authors="Jmods"
description="Realistically butcher everything in Minecraft!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.butchery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.butchery]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration