modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="medieval_deco"
version="1.2"
displayName="PlayTics Deco"
displayURL="https://patreon.com/playtics"
credits="PlayTics"
authors="PlayTics"
description="Deco"

[[dependencies.medieval_deco]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




